# https://github.com/lowlighter/metrics#-documentation
name: GitHub Profile Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: todorinskiz
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Brussels
          plugin_16personalities: yes
          plugin_16personalities_scores: yes
          plugin_16personalities_sections: personality,role,strategy
          plugin_16personalities_url: https://www.16personalities.com/profiles/a824cc0262a43
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 1400
          plugin_habits_facts: yes
          plugin_habits_from: 20000
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 6000
          plugin_languages_analysis_timeout_repositories: 30000
          plugin_languages_categories: markup, programming, data, prose
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 200
          plugin_languages_recent_categories: markup, programming, data, prose
          plugin_languages_recent_days: 3000
          plugin_languages_recent_load: 30000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 5
          plugin_stackoverflow_lines: 10
          plugin_stackoverflow_lines_snippet: 5
          plugin_stackoverflow_sections: answers-top, questions-top
          plugin_stackoverflow_user: 3983023
          plugin_traffic: yes
